#!/usr/bin/env python3
"""gen_sixstate_table.py -- T0 six-state census table (visibility pack, line E).

Renders schema/coverage-sixstate.v1.json into the T0 census artifact
experiments/active/visibility/T0-sixstate.md (format x state x regime, plus the
state histogram and the C_construct headline). Governance / workflow tooling,
stdlib-only: Python is tooling here, never the compiler stack. It does NOT read
or touch any C++/ODS.

IDEMPOTENT / DETERMINISTIC: the rendered markdown is a PURE function of the
sixstate JSON (its own $meta.repo_snapshot + a content sha256), never of the
wall clock or of the current git HEAD. So `render` twice on the same schema is
byte-identical, and the CI drift check (tools/visibility/check_visibility_drift.py)
can compare committed-vs-regenerated exactly. T0 drifts ONLY when the schema
changes.

The C_construct count rendered here is the number of six-state rows whose state
is 'constructed' (STRONG). In the current snapshot there are no duplicate roster
keys, so this equals the canonical C_construct emitted by
.trellis/scripts/coverage_metrics.py (best-state-across-variants over the roster
denominator). A cross-check line names that authority.

Subcommands
-----------
render [--out PATH]   write the T0 markdown (default: experiments/active/
                      visibility/T0-sixstate.md under the repo root).
--check               render to memory, compare with the committed artifact;
                      exit non-zero on drift (used by the CI regen/drift gate).
--self-test           hermetic: synthetic sixstate fixture; asserts the
                      histogram + constructed-count arithmetic and that the
                      render is idempotent (two renders byte-identical).
"""

import argparse
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path

# This file lives at <repo>/tools/visibility/gen_sixstate_table.py
REPO_ROOT = Path(__file__).resolve().parents[2]
SIXSTATE_JSON = REPO_ROOT / "schema" / "coverage-sixstate.v1.json"
DEFAULT_OUT = REPO_ROOT / "experiments" / "active" / "visibility" / "T0-sixstate.md"

# six-state ladder ([K-4]); index order is the maturity order.
LADDER = ["absent", "emittable", "dispatch-wired",
          "constructed-weak", "constructed", "covered"]
IDX = {s: i for i, s in enumerate(LADDER)}


# --- canonical hashing (mirrors coverage_metrics.py) -----------------------
def canonicalize(obj) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"))


def compute_hash(obj) -> str:
    return hashlib.sha256(canonicalize(obj).encode("utf-8")).hexdigest()


# --- pure render (no git, no clock) ----------------------------------------
def _key_tuple(row):
    return (row["op"], row["format"], row.get("engine", ""), row.get("regime", ""))


def _bar(n, ch="#"):
    return ch * n


def render_markdown(sixstate_obj) -> str:
    rows = sixstate_obj["states"]
    meta = sixstate_obj.get("$meta", {})

    # unknown-state guard (fail loud, not silent miscount).
    for r in rows:
        if r["state"] not in IDX:
            raise ValueError(f"unknown six-state {r['state']!r} for {_key_tuple(r)}")

    total = len(rows)
    hist = Counter(r["state"] for r in rows)
    constructed = hist.get("constructed", 0)
    weak = hist.get("constructed-weak", 0)
    # C_dispatch numerator = state >= dispatch-wired.
    c_dispatch = sum(v for s, v in hist.items() if IDX[s] >= IDX["dispatch-wired"])

    lines = []
    lines.append("# T0 -- Six-State Census (auto-generated)")
    lines.append("")
    lines.append("> DATA CELL (visibility line E). Generated by "
                 "`tools/visibility/gen_sixstate_table.py` from "
                 "`schema/coverage-sixstate.v1.json`. Do NOT hand-edit; rerun the "
                 "generator. Idempotent: pure function of the schema, no wall clock.")
    lines.append("")
    lines.append("## Provenance")
    lines.append("")
    lines.append(f"- schema repo_snapshot : `{meta.get('repo_snapshot', 'n/a')}`")
    lines.append(f"- schema snapshot date : `{meta.get('snapshot_commit_date', 'n/a')}`")
    lines.append(f"- sixstate sha256      : `{compute_hash(sixstate_obj)}`")
    lines.append(f"- ladder (low->high)   : {' < '.join(LADDER)}")
    lines.append("")

    # --- headline ----------------------------------------------------------
    lines.append("## Headline")
    lines.append("")
    lines.append(f"- **C_construct (STRONG 'constructed' rows) = {constructed} / {total}**")
    lines.append(f"- C_construct_plus (>= constructed-weak)  = {constructed + weak} / {total}")
    lines.append(f"- C_dispatch (>= dispatch-wired)          = {c_dispatch} / {total}")
    lines.append("")
    lines.append("> Cross-check: in this snapshot every roster key has exactly one "
                 "six-state row (no variant duplicates), so the 'constructed' row "
                 "count above equals the canonical C_construct from "
                 "`.trellis/scripts/coverage_metrics.py report` "
                 "(best-state-across-variants over the roster denominator). That "
                 "script is the authority for the paper number; this table is its "
                 "census view. Only 'constructed' (STRONG) feeds C_construct; "
                 "'constructed-weak' feeds C_construct_plus, never C_construct.")
    lines.append("")

    # --- state histogram ---------------------------------------------------
    lines.append("## State histogram (all rows)")
    lines.append("")
    lines.append("| state | count | share | bar |")
    lines.append("|---|---:|---:|---|")
    for s in LADDER:
        n = hist.get(s, 0)
        pct = (100.0 * n / total) if total else 0.0
        lines.append(f"| {s} | {n} | {pct:.1f}% | {_bar(n)} |")
    lines.append(f"| **total** | **{total}** | 100.0% | |")
    lines.append("")

    # --- by-op x state matrix ---------------------------------------------
    ops = sorted({r["op"] for r in rows})
    lines.append("## By-op x state matrix (row counts)")
    lines.append("")
    header = "| op | " + " | ".join(LADDER) + " | total |"
    sep = "|---|" + "|".join(["---:"] * len(LADDER)) + "|---:|"
    lines.append(header)
    lines.append(sep)
    for op in ops:
        op_rows = [r for r in rows if r["op"] == op]
        oc = Counter(r["state"] for r in op_rows)
        cells = " | ".join(str(oc.get(s, 0)) for s in LADDER)
        lines.append(f"| {op} | {cells} | {len(op_rows)} |")
    lines.append("")

    # --- full per-row table (format x state x regime) ----------------------
    lines.append("## Per-row census (format x engine x regime x state)")
    lines.append("")
    lines.append("| op | format | engine | regime | state |")
    lines.append("|---|---|---|---|---|")
    for r in sorted(rows, key=_key_tuple):
        eng = r.get("engine", "") or "-"
        reg = r.get("regime", "") or "-"
        lines.append(f"| {r['op']} | {r['format']} | {eng} | {reg} | {r['state']} |")
    lines.append("")

    # --- constructed roster (the C_construct evidence) ---------------------
    lines.append("## Constructed roster (the C_construct numerator)")
    lines.append("")
    lines.append("| # | op | format | engine | regime |")
    lines.append("|---:|---|---|---|---|")
    for i, r in enumerate(sorted((x for x in rows if x["state"] == "constructed"),
                                 key=_key_tuple), start=1):
        eng = r.get("engine", "") or "-"
        reg = r.get("regime", "") or "-"
        lines.append(f"| {i} | {r['op']} | {r['format']} | {eng} | {reg} |")
    lines.append("")

    return "\n".join(lines) + "\n"


# --- live IO paths ---------------------------------------------------------
def load_sixstate():
    return json.loads(SIXSTATE_JSON.read_text(encoding="utf-8"))


def cmd_render(args) -> int:
    text = render_markdown(load_sixstate())
    out = Path(args.out) if args.out else DEFAULT_OUT
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}")
    return 0


def cmd_check(_args) -> int:
    text = render_markdown(load_sixstate())
    if not DEFAULT_OUT.exists():
        print(f"DRIFT: {DEFAULT_OUT} missing (never rendered).", file=sys.stderr)
        return 1
    committed = DEFAULT_OUT.read_text(encoding="utf-8")
    if committed == text:
        print(f"OK: {DEFAULT_OUT.name} matches the schema (no drift).")
        return 0
    print(f"DRIFT: {DEFAULT_OUT} is stale vs schema/coverage-sixstate.v1.json. "
          f"Run: python3 tools/visibility/gen_sixstate_table.py render", file=sys.stderr)
    return 1


# --- self-test -------------------------------------------------------------
def cmd_self_test(_args) -> int:
    results = []

    def check(name, cond):
        results.append((name, bool(cond)))

    fixture = {
        "$meta": {"repo_snapshot": "deadbeef", "snapshot_commit_date": "2026-01-01"},
        "states": [
            {"op": "vec_dot", "format": "a", "state": "constructed"},
            {"op": "vec_dot", "format": "b", "state": "constructed"},
            {"op": "vec_dot", "format": "c", "state": "dispatch-wired"},
            {"op": "vec_dot", "format": "d", "state": "constructed-weak"},
            {"op": "gemm_tile", "format": "a", "engine": "rvv", "regime": "decode",
             "state": "constructed"},
            {"op": "gemm_tile", "format": "a", "engine": "rvv", "regime": "prefill",
             "state": "constructed"},
            {"op": "quantize_row", "format": "q", "state": "absent"},
        ],
    }
    text = render_markdown(fixture)
    check("headline: C_construct = 4/7 (the four 'constructed' rows)",
          "**C_construct (STRONG 'constructed' rows) = 4 / 7**" in text)
    check("headline: C_construct_plus = 5/7 (adds the one weak)",
          "C_construct_plus (>= constructed-weak)  = 5 / 7" in text)
    check("headline: C_dispatch = 6/7 (all but the absent quantize_row)",
          "C_dispatch (>= dispatch-wired)          = 6 / 7" in text)
    check("gemm_tile decode/prefill are DISTINCT rows (both constructed, both kept; "
          "each appears in the per-row census AND the constructed roster => 2x)",
          text.count("| gemm_tile | a | rvv | decode |") == 2
          and text.count("| gemm_tile | a | rvv | prefill |") == 2)
    check("render is idempotent (two renders byte-identical)",
          render_markdown(fixture) == text)
    # unknown state must raise, not miscount.
    raised = False
    try:
        render_markdown({"$meta": {}, "states": [{"op": "x", "format": "y",
                                                  "state": "bogus"}]})
    except ValueError:
        raised = True
    check("unknown state raises (no silent miscount)", raised)
    # canonical hash order-insensitive
    check("canonical hash order-insensitive",
          compute_hash({"a": 1, "b": 2}) == compute_hash({"b": 2, "a": 1}))

    ok = True
    for name, passed in results:
        print(f"[{'PASS' if passed else 'FAIL'}] {name}")
        ok = ok and passed
    print(f"\n{'ALL PASS' if ok else 'FAILURES PRESENT'} "
          f"({sum(p for _, p in results)}/{len(results)})")
    return 0 if ok else 1


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--check", action="store_true",
                        help="drift check committed artifact vs schema")
    sub = parser.add_subparsers(dest="cmd")
    p_render = sub.add_parser("render", help="write the T0 markdown")
    p_render.add_argument("--out", default=None)
    p_render.set_defaults(func=cmd_render)

    args = parser.parse_args(argv)
    if args.self_test:
        return cmd_self_test(args)
    if args.check:
        return cmd_check(args)
    if not getattr(args, "func", None):
        parser.print_help()
        return 2
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
