#!/usr/bin/env bash
# recompute_ledger_anchor.sh -- T2 ledger anchor recompute (visibility pack, line E).
#
# The [LED-1] per-family engineering ledger's FIRST data point is the IME family
# source size: raw wc-l = 2484 (docs/TianChen-RV_执行总纲v2.md line 239/241;
# [C2-1]/[C2-4] require it be reproducible). This script RECOMPUTES that anchor
# from the live tree via .trellis/scripts/family_ledger.py and records the
# recompute command + result into experiments/visibility/T2-ledger-anchor.md.
#
# Idempotent: the rendered markdown is a pure function of the IME source files +
# the family-dirs manifest (no wall clock), so a rerun on the same tree is
# byte-identical -- the CI drift check can compare committed-vs-regenerated.
#
# Exit non-zero if the recomputed raw wc-l != the pinned anchor (a self-check
# that the ledger's headline number still reproduces).
#
# Usage: tools/visibility/recompute_ledger_anchor.sh [--print-cmd-only]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

ANCHOR_EXPECTED=2484
LEDGER_REL=".trellis/scripts/family_ledger.py"
OUT_REL="experiments/visibility/T2-ledger-anchor.md"
# TCRV_T2_OUT lets the CI drift check render to a temp file (non-destructive compare).
OUT_ABS="${TCRV_T2_OUT:-${REPO_ROOT}/${OUT_REL}}"

RECOMPUTE_CMD="python3 ${LEDGER_REL} report --family IME"

if [[ "${1:-}" == "--print-cmd-only" ]]; then
  echo "cd \"${REPO_ROOT}\" && ${RECOMPUTE_CMD}   # code_LOC.raw_wc_l must == ${ANCHOR_EXPECTED}"
  exit 0
fi

# Run the ledger for IME and hand the JSON to python for extraction + rendering.
# The JSON travels via an env var (NOT a pipe): the heredoc below IS python's
# stdin (the program text), so stdin is unavailable for data.
LEDGER_JSON="$(cd "${REPO_ROOT}" && python3 "${LEDGER_REL}" report --family IME)"

ANCHOR_EXPECTED="${ANCHOR_EXPECTED}" RECOMPUTE_CMD="${RECOMPUTE_CMD}" \
  OUT_ABS="${OUT_ABS}" LEDGER_JSON="${LEDGER_JSON}" \
  python3 - <<'PY'
import json, os, sys

expected = int(os.environ["ANCHOR_EXPECTED"])
cmd = os.environ["RECOMPUTE_CMD"]
out = os.environ["OUT_ABS"]

report = json.loads(os.environ["LEDGER_JSON"])
fam = report["families"][0]
assert fam["family"] == "IME", fam["family"]
code = fam["code_LOC"]
tests = fam["test_LOC"]
raw = code["raw_wc_l"]
cloc = code["cloc_approx"]
files = code["files"]
msha = report["$meta"]["manifest_sha256"]
verdict = "PASS" if raw == expected else "FAIL"

lines = []
lines.append("# T2 -- Ledger Anchor Recompute (auto-generated)")
lines.append("")
lines.append("> DATA CELL (visibility line E). Generated by "
             "`tools/visibility/recompute_ledger_anchor.sh`. Do NOT hand-edit; "
             "rerun the script. Idempotent: pure function of the IME source files "
             "+ the family-dirs manifest, no wall clock.")
lines.append("")
lines.append("## What is the anchor?")
lines.append("")
lines.append("The [LED-1] per-family engineering ledger's FIRST data point "
             f"(`docs/TianChen-RV_执行总纲v2.md` line 239/241): the IME capability "
             f"family's hand-written source size. Headline = **raw wc-l = {expected}** "
             "(4 code dirs, EXCL the 5 CMakeLists.txt). [C2-1]/[C2-4] require it be "
             "reproducible; this cell reproduces it.")
lines.append("")
lines.append("## Recompute command")
lines.append("")
lines.append("```")
lines.append(f"{cmd}")
lines.append("```")
lines.append("")
lines.append("(runs the stdlib-only [LED-1] ledger; `code_LOC.raw_wc_l` is the "
             "anchor. `cloc` is not installed, so `cloc_approx` is a "
             "block-comment-stripped approximation -- the raw wc-l is the pinned "
             "anchor, cloc-approx is the [LED-1]-口径 secondary.)")
lines.append("")
lines.append("## Result")
lines.append("")
lines.append(f"- **verdict            : {verdict}** "
             f"(recomputed raw wc-l {raw} vs pinned anchor {expected})")
lines.append(f"- code_LOC raw wc-l   : {raw}  (files: {files})")
lines.append(f"- code_LOC cloc-approx: {cloc}  (secondary [LED-1]-口径; cloc absent)")
lines.append(f"- test_LOC raw wc-l   : {tests['raw_wc_l']}  (files: {tests['files']}; "
             "FULL footprint, uniform口径)")
by = tests.get("by_segment", {})
seg = " / ".join(f"{k} {v['raw_wc_l']}" for k, v in by.items())
if seg:
    lines.append(f"- test_LOC by segment : {seg}  (C2 cost-住址 split)")
lines.append(f"- family-dirs sha256  : {msha}")
lines.append("")
lines.append("## Notes")
lines.append("")
lines.append("- The 2484 anchor is raw wc-l, NOT cloc. The [LED-1]口径 is cloc "
             "(comments/blank/tests excluded); with cloc absent the ledger reports "
             "a cloc-approx (~1866) alongside. When quoting the marginal-cost curve, "
             "state which口径 (raw vs cloc) is in play.")
lines.append("- test_LOC is counted as the FULL test footprint (uniform口径, ruling "
             "2026-07-03), because dialect-verifier tests are a real part of the C2 "
             "generalization cost. It is a SEPARATE column from code_LOC, never "
             "folded into the 2484 anchor.")
lines.append("")

with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"wrote {out}")
print(f"[{verdict}] IME code_LOC raw wc-l = {raw} (expected {expected})")
sys.exit(0 if verdict == "PASS" else 1)
PY
