#!/usr/bin/env bash
# recompute_ledger_anchor.sh -- T2 ledger anchor recompute (visibility pack, line E).
#
# DUAL-NUMBER口径 (RESOLVED 2026-07-11 user ruling ④, 先查后改·禁静默替换):
#   * C2 FOUNDING-SLICE ANCHOR = raw wc-l 2484 -- FROZEN historical fact, reproduced at git
#     54465ee7 (2026-07-03, the commit that pinned the [LED-1] first data point). This is the
#     C2 marginal-cost curve's anchor (apples-to-apples with X-SCALAR's founding cost). It is
#     a 历史 slice 口径 and NEVER changes.
#   * LIVE `--family IME` raw wc-l = the CURRENT family size (5153 at 2026-07-11). The SAME 7
#     files that summed to 2484 @54465ee7 now sum higher because the IME family GREW (more MMA
#     op variants + emit paths). This is NOT a counting-口径 difference (same tool, same raw-wc-l
#     method); it is temporal family growth = C3' op-extension (family-internal), NOT C2
#     onboarding cost. Adopt the live recompute as the authoritative CURRENT number; keep 2484
#     labelled as the founding-slice C2 anchor -- do NOT silently replace it.
#
# [C2-1]/[C2-4] require the founding anchor be reproducible; this cell records BOTH numbers with
# their口径 labels + the drift explanation. The visibility drift gate compares committed-vs-
# regenerated (byte-exact), so a rerun on the same tree is byte-identical.
#
# Idempotent: the rendered markdown is a pure function of the IME source files + the family-dirs
# manifest (no wall clock). Exit 0 after rendering (the drift is EXPECTED family growth, not an
# error); the drift gate's byte-compare is the actual freshness check.
#
# Usage: tools/visibility/recompute_ledger_anchor.sh [--print-cmd-only]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# FROZEN C2 founding-slice anchor (历史 slice 口径, reproduced @git 54465ee7 / 2026-07-03).
FOUNDING_SLICE_ANCHOR=2484
FOUNDING_SLICE_REF=54465ee7
LEDGER_REL=".trellis/scripts/family_ledger.py"
OUT_REL="experiments/active/visibility/T2-ledger-anchor.md"
# WEFT_T2_OUT lets the CI drift check render to a temp file (non-destructive compare).
OUT_ABS="${WEFT_T2_OUT:-${REPO_ROOT}/${OUT_REL}}"

RECOMPUTE_CMD="python3 ${LEDGER_REL} report --family IME"

if [[ "${1:-}" == "--print-cmd-only" ]]; then
  echo "cd \"${REPO_ROOT}\" && ${RECOMPUTE_CMD}   # code_LOC.raw_wc_l = LIVE family size; C2 founding-slice anchor = ${FOUNDING_SLICE_ANCHOR} (frozen @${FOUNDING_SLICE_REF})"
  exit 0
fi

# Run the ledger for IME and hand the JSON to python for extraction + rendering.
# The JSON travels via an env var (NOT a pipe): the heredoc below IS python's
# stdin (the program text), so stdin is unavailable for data.
LEDGER_JSON="$(cd "${REPO_ROOT}" && python3 "${LEDGER_REL}" report --family IME)"

FOUNDING_SLICE_ANCHOR="${FOUNDING_SLICE_ANCHOR}" FOUNDING_SLICE_REF="${FOUNDING_SLICE_REF}" \
  RECOMPUTE_CMD="${RECOMPUTE_CMD}" OUT_ABS="${OUT_ABS}" LEDGER_JSON="${LEDGER_JSON}" \
  python3 - <<'PY'
import json, os, sys

founding = int(os.environ["FOUNDING_SLICE_ANCHOR"])
founding_ref = os.environ["FOUNDING_SLICE_REF"]
cmd = os.environ["RECOMPUTE_CMD"]
out = os.environ["OUT_ABS"]

report = json.loads(os.environ["LEDGER_JSON"])
fam = report["families"][0]
assert fam["family"] == "IME", fam["family"]
code = fam["code_LOC"]
tests = fam["test_LOC"]
raw = code["raw_wc_l"]          # LIVE current family size
cloc = code["cloc_approx"]
files = code["files"]
msha = report["$meta"]["manifest_sha256"]
drift = raw - founding

lines = []
lines.append("# T2 -- Ledger Anchor Recompute (auto-generated)")
lines.append("")
lines.append("> DATA CELL (visibility line E). Generated by "
             "`tools/visibility/recompute_ledger_anchor.sh`. Do NOT hand-edit; "
             "rerun the script. Idempotent: pure function of the IME source files "
             "+ the family-dirs manifest, no wall clock.")
lines.append("")
lines.append("## Two numbers, two口径 (RESOLVED 2026-07-11 user ruling)")
lines.append("")
lines.append(f"- **C2 founding-slice anchor = raw wc-l {founding}** (历史 slice 口径; FROZEN, "
             f"reproduced @git `{founding_ref}` / 2026-07-03 -- the commit that pinned the "
             "[LED-1] first data point). This is the **C2 marginal-cost curve anchor** "
             "(apples-to-apples with X-SCALAR's founding cost) and never changes. "
             "`_attic/docs/canon/Weft-RV_执行总纲v2.md` §8 recompute table = this slice.")
lines.append(f"- **LIVE `--family IME` raw wc-l = {raw}** (current family size; the authoritative "
             "recompute of the live tree). The SAME 7 files that summed to "
             f"{founding} @`{founding_ref}` now sum to {raw} (delta **+{drift}**) because the IME "
             "family GREW -- more MMA op variants + emit paths. This is **NOT a counting-口径 "
             "difference** (same tool, same raw-wc-l method); it is temporal family growth = "
             "**C3' op-extension (family-internal), NOT C2 onboarding cost**. cloc-approx = "
             f"{cloc}.")
lines.append("")
lines.append("**禁静默替换 2484**: the founding-slice anchor stays the C2 data point; the live "
             f"{raw} is the informational current size. When quoting the C2 marginal-cost curve, "
             f"use the founding slice ({founding} raw). When quoting current family size, use the "
             f"live recompute ({raw} raw).")
lines.append("")
lines.append("## Recompute command")
lines.append("")
lines.append("```")
lines.append(f"{cmd}")
lines.append("```")
lines.append("")
lines.append("(runs the stdlib-only [LED-1] ledger; `code_LOC.raw_wc_l` = LIVE family size. "
             "`cloc` is not installed, so `cloc_approx` is a block-comment-stripped approximation "
             "-- raw wc-l is the pinned口径, cloc-approx is the [LED-1]-口径 secondary.)")
lines.append("")
lines.append("## Result")
lines.append("")
lines.append(f"- **verdict            : RECORDED** (live raw wc-l {raw}; C2 founding-slice anchor "
             f"{founding} frozen @{founding_ref}; delta +{drift} = C3' family extension, expected)")
lines.append(f"- code_LOC raw wc-l   : {raw}  (files: {files}; LIVE current family size)")
lines.append(f"- C2 founding anchor  : {founding}  (历史 slice 口径, frozen @{founding_ref})")
lines.append(f"- code_LOC cloc-approx: {cloc}  (secondary [LED-1]-口径; cloc absent)")
lines.append(f"- test_LOC raw wc-l   : {tests['raw_wc_l']}  (files: {tests['files']}; "
             "FULL footprint, uniform口径)")
by = tests.get("by_segment", {})
seg = " / ".join(f"{k} {v['raw_wc_l']}" for k, v in by.items())
if seg:
    lines.append(f"- test_LOC by segment : {seg}  (C2 cost-住址 split)")
lines.append(f"- family-dirs sha256  : {msha}")
lines.append("")
lines.append("## Notes")
lines.append("")
lines.append(f"- The {founding} founding anchor is raw wc-l, NOT cloc. The [LED-1]口径 is cloc "
             "(comments/blank/tests excluded); with cloc absent the ledger reports a cloc-approx "
             "alongside. When quoting the marginal-cost curve, state which口径 (raw vs cloc).")
lines.append("- test_LOC is counted as the FULL test footprint (uniform口径, ruling 2026-07-03), "
             "because dialect-verifier tests are a real part of the C2 generalization cost. It is "
             f"a SEPARATE column from code_LOC, never folded into the {founding} anchor.")
lines.append("- Anchor drift (先查后改, 2026-07-11): live > founding is EXPECTED (family grows). "
             "The C2 curve anchor stays frozen at the founding slice; the drift gate's byte-compare "
             "keeps this cell in sync with the live tree. See "
             "`docs/method/C2_marginal_cost_ledger.md` appendix (IME row anchor note).")
lines.append("")

with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"wrote {out}")
print(f"[RECORDED] IME live raw wc-l = {raw}; C2 founding-slice anchor {founding} "
      f"(frozen @{founding_ref}); delta +{drift} = C3' family extension (expected)")
sys.exit(0)
PY
