// AUTO-GENERATED by tune_block_dot.py -- the on-board microbench for ONE
// (kernel, capability-march) tune run. FILTER-then-RANK: each candidate is
// GATED byte-exact vs ggml's real kernel (a SEPARATE TU, kern_ggml) over MANY n
// and MANY trials under the SAME -ffp-contract=fast the kernel ships with -- a
// candidate that drifts even ~1 ULP is INELIGIBLE (not a valid drop-in) and is
// dropped BEFORE timing. The record therefore can NEVER name a non-exact shape.
// Then the surviving candidates are timed best-of-N min (taskset-pinned).
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <time.h>
#include <riscv_vector.h>
extern "C" void kern_ggml(size_t, float *, const uint8_t *, const uint8_t *);
extern "C" void tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_mf4_f1_robust(size_t, float *, const uint8_t *, const uint8_t *);
extern "C" void tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_mf4_f2_robust(size_t, float *, const uint8_t *, const uint8_t *);
extern "C" void tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_mf4_f4_robust(size_t, float *, const uint8_t *, const uint8_t *);
extern "C" void tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_m1_f1_robust(size_t, float *, const uint8_t *, const uint8_t *);
extern "C" void tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_m1_f2_robust(size_t, float *, const uint8_t *, const uint8_t *);
extern "C" void tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_m1_f4_robust(size_t, float *, const uint8_t *, const uint8_t *);
static uint32_t rng = 0x2468ace0u;
static uint32_t xr() { rng ^= rng << 13; rng ^= rng >> 17; rng ^= rng << 5; return rng; }
static uint16_t rfp16() {
  uint16_t s = (xr() & 1) << 15, e = (uint16_t)(xr() % 31), m = (uint16_t)(xr() & 0x3FF);
  return s | (e << 10) | m;
}
static void fill(uint8_t *vx, uint8_t *vy, int nb, int xs, int ys, int xq, int yq) {
  for (int ib = 0; ib < nb; ++ib) {
    uint8_t *xb = vx + (size_t)ib * xs, *yb = vy + (size_t)ib * ys;
    uint16_t d;
    d = rfp16(); memcpy(xb, &d, 2);
    d = rfp16(); memcpy(yb, &d, 2);
    if (xs == 20) { d = rfp16(); memcpy(xb + 2, &d, 2); }  /* q4_1 weight min */
    if (ys == 36) { d = rfp16(); memcpy(yb + 2, &d, 2); }  /* q8_1 act sum */
    for (int i = 0; i < xq; ++i) xb[(xs - xq) + i] = (uint8_t)(xr() & 0xFF);
    for (int i = 0; i < yq; ++i) yb[(ys - yq) + i] = (uint8_t)(xr() & 0xFF);
  }
}
typedef void (*kfn)(size_t, float *, const uint8_t *, const uint8_t *);
struct E { const char *name; kfn fn; double best; int eligible; };
static double now() { struct timespec t; clock_gettime(CLOCK_MONOTONIC, &t); return t.tv_sec * 1e9 + t.tv_nsec; }
static double tb(kfn fn, size_t n, int it, const uint8_t *vx, const uint8_t *vy) {
  double t0 = now(); float s; for (int i = 0; i < it; i++) fn(n, &s, vx, vy); return (now() - t0) / it;
}
static int beq(float a, float b) { uint32_t x, y; memcpy(&x, &a, 4); memcpy(&y, &b, 4); return x == y; }
int main() {
  const int xs = 20, ys = 36, xq = 16, yq = 32;
  const int timing_n = 4096, iters = 2000, reps = 200;
  struct E ks[] = {
    {"mf4_f1_robust", tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_mf4_f1_robust, 1e18, 1},
    {"mf4_f2_robust", tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_mf4_f2_robust, 1e18, 1},
    {"mf4_f4_robust", tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_mf4_f4_robust, 1e18, 1},
    {"m1_f1_robust", tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_m1_f1_robust, 1e18, 1},
    {"m1_f2_robust", tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_m1_f2_robust, 1e18, 1},
    {"m1_f4_robust", tcrv_emitc_ggml_vec_dot_q4_1_q8_1_kernel_ggml_vec_dot_q4_1_q8_1_m1_f4_robust, 1e18, 1},
  };
  const int K = sizeof(ks) / sizeof(ks[0]);

  // GATE: byte-exact vs ggml (separate TU) over many n x many trials at =fast.
  int gate_ns[] = {32, 64, 128, 256, 512, 1024, 2048, 4096, 8192};
  const int NN = sizeof(gate_ns) / sizeof(gate_ns[0]);
  for (int t = 0; t < 200; ++t) {
    for (int j = 0; j < NN; ++j) {
      int n = gate_ns[j], nb = n / 32;
      uint8_t *vx = (uint8_t *)malloc((size_t)nb * xs), *vy = (uint8_t *)malloc((size_t)nb * ys);
      fill(vx, vy, nb, xs, ys, xq, yq);
      float ref = 0; kern_ggml(n, &ref, vx, vy);
      for (int k = 0; k < K; ++k) {
        if (!ks[k].eligible) continue;
        float g = 0; ks[k].fn(n, &g, vx, vy);
        if (!beq(g, ref)) ks[k].eligible = 0;
      }
      free(vx); free(vy);
    }
  }
  int n_eligible = 0;
  for (int k = 0; k < K; ++k) {
    printf("GATE %s %s\n", ks[k].name, ks[k].eligible ? "exact" : "DRIFT-ineligible");
    if (ks[k].eligible) n_eligible++;
  }
  printf("gate_done %d/%d candidates byte-exact vs ggml (=fast, many n)\n", n_eligible, K);
  if (n_eligible == 0) { printf("NO_ELIGIBLE\n"); return 1; }

  // RANK: time only the ELIGIBLE survivors + the ggml baseline.
  int nb = timing_n / 32;
  uint8_t *vx = (uint8_t *)malloc((size_t)nb * xs), *vy = (uint8_t *)malloc((size_t)nb * ys);
  fill(vx, vy, nb, xs, ys, xq, yq);
  double ggml_best = 1e18;
  for (int k = 0; k < K; ++k) for (int i = 0; i < iters; i++) { float s; if (ks[k].eligible) ks[k].fn(timing_n, &s, vx, vy); }
  for (int i = 0; i < iters; i++) { float s; kern_ggml(timing_n, &s, vx, vy); }
  for (int r = 0; r < reps; r++) {
    double pg = tb(kern_ggml, timing_n, iters, vx, vy); if (pg < ggml_best) ggml_best = pg;
    for (int k = 0; k < K; k++) {
      if (!ks[k].eligible) continue;
      double p = tb(ks[k].fn, timing_n, iters, vx, vy); if (p < ks[k].best) ks[k].best = p;
    }
  }
  printf("RESULT ggml(real) %.1f\n", ggml_best);
  for (int k = 0; k < K; ++k) if (ks[k].eligible) printf("RESULT %s %.1f\n", ks[k].name, ks[k].best);
  free(vx); free(vy);
  return 0;
}
