// AUTO-GENERATED by tune_gemm.py -- the on-board GEMM M-block tune microbench.
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <time.h>
#include <riscv_vector.h>
static const int QK=32,Q4=18,Q8=34;
static inline float h2f(uint16_t h){_Float16 x;memcpy(&x,&h,2);return (float)x;}
static inline uint16_t f2h(float f){_Float16 x=(_Float16)f;uint16_t h;memcpy(&h,&x,2);return h;}
extern "C" void gemm_m1(size_t,float*,const uint8_t*,const uint8_t*,size_t,size_t,size_t,size_t,size_t);
extern "C" void gemm_m2(size_t,float*,const uint8_t*,const uint8_t*,size_t,size_t,size_t,size_t,size_t);
extern "C" void gemm_m4(size_t,float*,const uint8_t*,const uint8_t*,size_t,size_t,size_t,size_t,size_t);
extern "C" void gemm_m6(size_t,float*,const uint8_t*,const uint8_t*,size_t,size_t,size_t,size_t,size_t);
extern "C" void gemm_m8(size_t,float*,const uint8_t*,const uint8_t*,size_t,size_t,size_t,size_t,size_t);
// The per-(row,col) reference: ggml_vec_dot_q4_0_q8_0 (the real used VLEN=128 path).
static float vd(int n,const uint8_t*vx,const uint8_t*vy){int nb=n/QK;float s=0;size_t vl=16;
 for(int ib=0;ib<nb;ib++){const uint8_t*xb=vx+(size_t)ib*Q4,*yb=vy+(size_t)ib*Q8;
  vuint8m1_t tx=__riscv_vle8_v_u8m1(xb+2,vl);vint8m1_t y0=__riscv_vle8_v_i8m1((const int8_t*)(yb+2),vl),y1=__riscv_vle8_v_i8m1((const int8_t*)(yb+18),vl);
  vuint8m1_t a=__riscv_vand_vx_u8m1(tx,0x0F,vl),l=__riscv_vsrl_vx_u8m1(tx,4,vl);
  vint8m1_t v0=__riscv_vsub_vx_i8m1(__riscv_vreinterpret_v_u8m1_i8m1(a),8,vl),v1=__riscv_vsub_vx_i8m1(__riscv_vreinterpret_v_u8m1_i8m1(l),8,vl);
  vint16m2_t p=__riscv_vwmul_vv_i16m2(v0,y0,vl);p=__riscv_vwmacc_vv_i16m2(p,v1,y1,vl);
  vint32m1_t sd=__riscv_vmv_v_x_i32m1(0,1),r=__riscv_vwredsum_vs_i16m2_i32m1(p,sd,vl);int32_t si=__riscv_vmv_x_s_i32m1_i32(r);
  s=s+((float)si*h2f(*(const uint16_t*)xb))*h2f(*(const uint16_t*)yb);}return s;}
static uint64_t R=0x123456789abcdef0ULL;static uint32_t xr(){R^=R<<13;R^=R>>7;R^=R<<17;return R>>32;}
static void fw(uint8_t*r,int nb){for(int i=0;i<nb;i++){uint8_t*b=r+(size_t)i*Q4;*(uint16_t*)b=f2h(((int)(xr()%2000)-1000)/4096.0f);for(int j=0;j<16;j++)b[2+j]=xr()&0xFF;}}
static void fc(uint8_t*c,int nb){for(int i=0;i<nb;i++){uint8_t*b=c+(size_t)i*Q8;*(uint16_t*)b=f2h(((int)(xr()%2000)-1000)/8192.0f);for(int j=0;j<32;j++)b[2+j]=(int8_t)(xr()&0xFF);}}
static double now(){struct timespec t;clock_gettime(CLOCK_MONOTONIC,&t);return t.tv_sec*1e9+t.tv_nsec;}
typedef void(*fn)(size_t,float*,const uint8_t*,const uint8_t*,size_t,size_t,size_t,size_t,size_t);
struct E{const char*name;int m;fn f;double best;int eligible;};
static int beq(float a,float b){uint32_t x,y;memcpy(&x,&a,4);memcpy(&y,&b,4);return x==y;}
// Build random W (nr rows) + A (nc cols) at contraction n; reference into ref[].
static void build(int n,int nr,int nc,uint8_t**W,uint8_t**A,float**ref,
                  size_t*bx,size_t*by){int nb=n/QK;*bx=(size_t)nb*Q4;*by=(size_t)nb*Q8;
 *W=(uint8_t*)malloc((size_t)nr**bx);*A=(uint8_t*)malloc((size_t)nc**by);*ref=(float*)malloc((size_t)nr*nc*sizeof(float));
 for(int r=0;r<nr;r++)fw(*W+(size_t)r**bx,nb);for(int c=0;c<nc;c++)fc(*A+(size_t)c**by,nb);
 for(int r=0;r<nr;r++)for(int c=0;c<nc;c++)(*ref)[(size_t)r*nc+c]=vd(n,*W+(size_t)r**bx,*A+(size_t)c**by);}
int main(){
  struct E ks[]={
    {"M1",1,gemm_m1,1e30,1},
    {"M2",2,gemm_m2,1e30,1},
    {"M4",4,gemm_m4,1e30,1},
    {"M6",6,gemm_m6,1e30,1},
    {"M8",8,gemm_m8,1e30,1},
  };
  const int K=sizeof(ks)/sizeof(ks[0]);
  // GATE: byte-exact vs per-(row,col) vec_dot over several shapes (incl. tail nc).
  int gate_n[]={32,256,1024,4096}; int gate_nr[]={8,3,8,8}; int gate_nc[]={4,7,13,6};
  const int NG=sizeof(gate_n)/sizeof(gate_n[0]);
  for(int g=0;g<NG;g++){int n=gate_n[g],nr=gate_nr[g],nc=gate_nc[g];
    uint8_t*W,*A;float*ref;size_t bx,by;build(n,nr,nc,&W,&A,&ref,&bx,&by);
    float*o=(float*)malloc((size_t)nr*nc*sizeof(float));
    for(int k=0;k<K;k++){if(!ks[k].eligible)continue;
      memset(o,0,(size_t)nr*nc*sizeof(float));
      ks[k].f(n,o,W,A,by,nr,nc,bx,(size_t)nc);
      for(int i=0;i<nr*nc;i++)if(!beq(o[i],ref[i])){ks[k].eligible=0;break;}}
    free(W);free(A);free(ref);free(o);}
  int ne=0;for(int k=0;k<K;k++){printf("GATE M=%d %s\n",ks[k].m,ks[k].eligible?"exact":"DRIFT-ineligible");if(ks[k].eligible)ne++;}
  printf("gate_done %d/%d M candidates byte-exact vs per-(row,col) vec_dot\n",ne,K);
  if(ne==0){printf("NO_ELIGIBLE\n");return 1;}
  // RANK (INC-10's INTERLEAVED method -- the fix for shared-board contention):
  // EVERY eligible M + its per-output vec_dot baseline are measured INSIDE each
  // rep, on a per-M FIXED column block (nc=M, the per-(row,col) workload), so a
  // time-varying contention spike hits all candidates in the SAME window and
  // CANCELS in the per-output ns ratio. Each M owns its own pre-built W/A/o; the
  // rep loop times each M's gemm (best-of-N min) and ALSO a SHARED vec_dot
  // baseline at a FIXED reference shape (nr x 8 cols at K) so the baseline
  // is one stable number, not a per-M noisy re-measure. ns/output is the
  // per-output reuse unit (the research's metric).
  const int n=4096,nr=8,reps=3000;
  // Per-M pre-built buffers (nc=M).
  uint8_t*W[16],*A[16];float*o[16];size_t bx[16],by[16];
  for(int k=0;k<K;k++){if(!ks[k].eligible)continue;int nc=ks[k].m;float*ref;
    build(n,nr,nc,&W[k],&A[k],&ref,&bx[k],&by[k]);free(ref);
    o[k]=(float*)malloc((size_t)nr*nc*sizeof(float));}
  // The SHARED vec_dot baseline workload: a fixed nr x BASE_NC tile at K, the
  // per-(row,col) used path. One stable per-output number measured interleaved.
  const int base_nc=8;uint8_t*bW,*bA;float*bref;size_t bbx,bby;
  build(n,nr,base_nc,&bW,&bA,&bref,&bbx,&bby);free(bref);
  float*bo=(float*)malloc((size_t)nr*base_nc*sizeof(float));
  double bestg[16];for(int k=0;k<K;k++)bestg[k]=1e30;double bestv=1e30;
  volatile float sk=0;
  // warm every candidate + baseline.
  for(int w=0;w<2000;w++){for(int k=0;k<K;k++){if(!ks[k].eligible)continue;
      ks[k].f(n,o[k],W[k],A[k],by[k],nr,ks[k].m,bx[k],(size_t)ks[k].m);sk+=o[k][0];}
    for(int i=0;i<nr;i++)for(int c=0;c<base_nc;c++)bo[(size_t)i*base_nc+c]=vd(n,bW+(size_t)i*bbx,bA+(size_t)c*bby);sk+=bo[0];}
  // INTERLEAVED rep loop: each rep times every M's gemm AND the baseline.
  for(int r=0;r<reps;r++){
    for(int k=0;k<K;k++){if(!ks[k].eligible)continue;int nc=ks[k].m;
      double t=now();ks[k].f(n,o[k],W[k],A[k],by[k],nr,nc,bx[k],(size_t)nc);double e=(now()-t)/((double)nr*nc);
      if(e<bestg[k])bestg[k]=e;sk+=o[k][0];}
    double t=now();for(int i=0;i<nr;i++)for(int c=0;c<base_nc;c++)bo[(size_t)i*base_nc+c]=vd(n,bW+(size_t)i*bbx,bA+(size_t)c*bby);
    double e=(now()-t)/((double)nr*base_nc);if(e<bestv)bestv=e;sk+=bo[0];}
  for(int k=0;k<K;k++){if(!ks[k].eligible)continue;
    printf("RESULT M=%d gemm_ns=%.1f vecdot_ns=%.1f speedup=%.3f\n",
           ks[k].m,bestg[k],bestv,bestv/bestg[k]);}
  return 0;
}
