// INC-37 iq3_s COMPILER-KNOB control (ssh rvv): the grid DenseArray attr is the LIVE
// knob attr -> emitted const -> HW result. We compile TWO kernels from TWO typed bodies
// that differ ONLY in the $grid attr (the perturbed body has grid[5]'s low byte +1,
// 0x01010301 -> 0x01010302), regenerated by the compiler into a DISTINCT symbol. On the
// board, with inputs that drive grid index 5, the REAL-attr kernel matches a reference
// built with the REAL grid, the PERTURBED-attr kernel matches a reference built with the
// PERTURBED grid, and the two HW results DIVERGE. A hardcoded-table emitter (where the
// attr is dead) could NOT diverge -> the grid attr genuinely flows attr -> const -> HW.

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <cstdlib>

#define QK_K 256
#define IQ3S_N_SCALE (QK_K/64)
typedef struct {
  uint16_t d; uint8_t qs[QK_K/4]; uint8_t qh[QK_K/32];
  uint8_t signs[QK_K/8]; uint8_t scales[IQ3S_N_SCALE];
} block_iq3_s;
typedef struct { float d; int8_t qs[QK_K]; int16_t bsums[QK_K/16]; } block_q8_K;
static const uint8_t kmask_iq2xs[8] = {1,2,4,8,16,32,64,128};

// the REAL grid (verbatim ggml-common.h iq3s_grid[512]) -- declared in inc37_validate
// is local; we re-embed only what we need by reading the harness's table indirectly.
// To keep this TU self-contained, embed the two grids' ONLY differing region: entry 5.
// We build the full grids from the validate harness's table via a shared header-free
// copy: read entries from the linked real kernel is not possible, so embed both grids.
#include "inc37_grids.h"   // defines iq3s_grid_real[512] and iq3s_grid_pert[512]

static inline float fp16_to_fp32(uint16_t h){ _Float16 hf; memcpy(&hf,&h,2); return (float)hf; }

extern "C" void
tcrv_emitc_ggml_vec_dot_iq3_s_q8_K_kernel_ggml_vec_dot_iq3_s_q8_K(
    size_t n, float *s, const uint8_t *vx, const uint8_t *vy);
extern "C" void
tcrv_emitc_ggml_vec_dot_iq3_s_q8_K_PERT_kernel_ggml_vec_dot_iq3_s_q8_K_PERT(
    size_t n, float *s, const uint8_t *vx, const uint8_t *vy);

static void ref(int n, float *s, const void *vx, const void *vy, const uint32_t *grid) {
  const block_iq3_s *x = (const block_iq3_s *)vx;
  const block_q8_K *y = (const block_q8_K *)vy;
  const int nb = n / QK_K;
  float sumf = 0.f;
  for (int i = 0; i < nb; ++i) {
    const float d = fp16_to_fp32(x[i].d) * y[i].d;
    const uint8_t *qs = x[i].qs, *qh = x[i].qh, *signs = x[i].signs;
    const int8_t *q8 = y[i].qs;
    int32_t bsum = 0;
    for (int ib32 = 0; ib32 < QK_K/32; ib32 += 2) {
      const uint32_t ls1 = 2*(x[i].scales[ib32/2] & 0xf) + 1;
      const uint32_t ls2 = 2*(x[i].scales[ib32/2] >>  4) + 1;
      int32_t sumi = 0;
      for (int l = 0; l < 4; ++l) {
        const uint8_t *g1 = (const uint8_t *)(grid + (qs[2*l+0] | ((qh[ib32+0] << (8-2*l)) & 256)));
        const uint8_t *g2 = (const uint8_t *)(grid + (qs[2*l+1] | ((qh[ib32+0] << (7-2*l)) & 256)));
        for (int j = 0; j < 4; ++j) {
          sumi += g1[j]*q8[j+0]*(signs[l] & kmask_iq2xs[j+0]?-1:1);
          sumi += g2[j]*q8[j+4]*(signs[l] & kmask_iq2xs[j+4]?-1:1);
        }
        q8 += 8;
      }
      qs += 8; signs += 4; bsum += sumi*ls1; sumi = 0;
      for (int l = 0; l < 4; ++l) {
        const uint8_t *g1 = (const uint8_t *)(grid + (qs[2*l+0] | ((qh[ib32+1] << (8-2*l)) & 256)));
        const uint8_t *g2 = (const uint8_t *)(grid + (qs[2*l+1] | ((qh[ib32+1] << (7-2*l)) & 256)));
        for (int j = 0; j < 4; ++j) {
          sumi += g1[j]*q8[j+0]*(signs[l] & kmask_iq2xs[j+0]?-1:1);
          sumi += g2[j]*q8[j+4]*(signs[l] & kmask_iq2xs[j+4]?-1:1);
        }
        q8 += 8;
      }
      qs += 8; signs += 4; bsum += sumi*ls2;
    }
    sumf += d*bsum;
  }
  *s = sumf;
}

static uint64_t st = 0xc0ffee99ULL;
static uint32_t xr(){ st^=st<<13; st^=st>>7; st^=st<<17; return (uint32_t)(st>>32); }
static int beq(float a, float b){ uint32_t ua,ub; memcpy(&ua,&a,4); memcpy(&ub,&b,4); return ua==ub; }

int main() {
  int nb = 8, n = nb*QK_K;
  block_iq3_s *X = (block_iq3_s *)malloc(nb*sizeof(block_iq3_s));
  block_q8_K *Y = (block_q8_K *)malloc(nb*sizeof(block_q8_K));
  // drive grid index 5 in many groups: qs index byte = 5, qh bit cleared (so idx = 5).
  for (int b = 0; b < nb; ++b) {
    uint16_t exp = (uint16_t)(13);
    X[b].d = (uint16_t)((exp<<10) | (xr()&0x3ff));
    for (int j = 0; j < QK_K/4; ++j) X[b].qs[j] = 5;     // index 5
    for (int j = 0; j < QK_K/32; ++j) X[b].qh[j] = 0;    // no high bit -> idx stays 5
    for (int j = 0; j < QK_K/8; ++j) X[b].signs[j] = 0;  // no sign flip
    for (int j = 0; j < IQ3S_N_SCALE; ++j) X[b].scales[j] = (uint8_t)(0x11);
    Y[b].d = fp16_to_fp32((uint16_t)((13<<10) | (xr()&0x3ff)));
    for (int j = 0; j < QK_K; ++j) Y[b].qs[j] = (int8_t)(50 + (xr()%50));
  }

  float s_real_kernel = 0.f, s_pert_kernel = 0.f, s_real_ref = 0.f, s_pert_ref = 0.f;
  tcrv_emitc_ggml_vec_dot_iq3_s_q8_K_kernel_ggml_vec_dot_iq3_s_q8_K(
      (size_t)n, &s_real_kernel, (const uint8_t *)X, (const uint8_t *)Y);
  tcrv_emitc_ggml_vec_dot_iq3_s_q8_K_PERT_kernel_ggml_vec_dot_iq3_s_q8_K_PERT(
      (size_t)n, &s_pert_kernel, (const uint8_t *)X, (const uint8_t *)Y);
  ref(n, &s_real_ref, X, Y, iq3s_grid_real);
  ref(n, &s_pert_ref, X, Y, iq3s_grid_pert);

  printf("REAL-attr kernel      = %.5f   (real-table ref = %.5f) -> %s\n",
         s_real_kernel, s_real_ref, beq(s_real_kernel, s_real_ref) ? "MATCH" : "MISMATCH");
  printf("PERTURBED-attr kernel = %.5f   (pert-table ref = %.5f) -> %s\n",
         s_pert_kernel, s_pert_ref, beq(s_pert_kernel, s_pert_ref) ? "MATCH" : "MISMATCH");
  bool diverge = !beq(s_real_kernel, s_pert_kernel);
  printf("real-attr vs perturbed-attr -> %s (attr is the live knob)\n",
         diverge ? "DIVERGES" : "MATCHES (BUG: attr is dead!)");
  bool ok = beq(s_real_kernel, s_real_ref) && beq(s_pert_kernel, s_pert_ref) && diverge;
  printf("RESULT: %s\n", ok ? "KNOB LIVE (attr -> const -> HW)" : "KNOB CONTROL FAILED");
  free(X); free(Y);
  return ok ? 0 : 1;
}
