#ifndef TIANCHENRV_CONVERSION_EMITC_TCRVEMITCLOWERABLEOPINTERFACE_H
#define TIANCHENRV_CONVERSION_EMITC_TCRVEMITCLOWERABLEOPINTERFACE_H

#include "mlir/IR/OpDefinition.h"
#include "llvm/ADT/StringRef.h"

#include "TianChenRV/Conversion/EmitC/TCRVEmitCLowerableOpInterface.h.inc"

#endif // TIANCHENRV_CONVERSION_EMITC_TCRVEMITCLOWERABLEOPINTERFACE_H
